env:
  matrix:
    - NODE_VERSION=0.10
    - NODE_VERSION=0.11
  global:
    - STRICT_REQUIRE=1

install:
  - test $TRAVIS_OS_NAME = "osx" && brew install nvm && source $(brew --prefix nvm)/nvm.sh || test $TRAVIS_OS_NAME = "linux"
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
  - npm install -g grunt-cli
  - npm install

os:
  - osx
  - linux

matrix:
  allow_failures:
    - os: osx
    - env: "NODE_VERSION=0.11"

script: grunt travis
